export const portfolioProyects = [
  /*   {
    id: 0,
    name: "SimpleChat",
    img: "./assets/proy00.jpg",
    url: "https://simple-chat-tkrk.onrender.com/",
    description1: "Microservicio SimpleChat",
    description2: "Backend de chat basado en node. Con persistencia en DB. Frontend React.js",
    tech: ["node", "sqlite", "express", "react", "typescript", "turso", "render"],
  }, */
  {
    id: 1,
    name: "weather app",
    img: "./assets/proy01.jpg",
    url: "https://weather-app-next-flax.vercel.app/",
    description1: "Weather App",
    description2: "Full Stack app with Next.js, TypeScript and Tailwind CSS. API Consuming.",
    tech: ["next", "tailwind", "react", "typescript", "vercel"],
  },
  {
    id: 2,
    name: "Portfolio Profesional Genérico",
    img: "./assets/proy02.jpg",
    url: "https://sergioortega.com.ar/portfolio/web-portfolio-generico/",
    description1: "Portfolio Profesional Genérico",
    description2: "Frontend with react and Bootstrap",
    tech: ["react", "bootstrap"],
  },
  {
    id: 3,
    name: "E-commerce Simple",
    img: "./assets/proy03.jpg",
    url: "https://sergioortega.com.ar/portfolio/web-pedidos/",
    description1: "E-commerce Simple",
    description2: "Frontend with react and Bootstrap",
    tech: ["react", "bootstrap"],
  },
  {
    id: 4,
    name: "Web app de Notas",
    img: "./assets/proy04.jpg",
    url: "https://sergioortega.com.ar/portfolio/notas/notas.html",
    description1: "Web app de Notas",
    description2: "Frontend with react and Bootstrap",
    tech: ["react", "bootstrap"],
  },
  {
    id: 5,
    name: "Frases de Los Simpsons",
    img: "./assets/proy05.jpg",
    url: "https://sergioortega.com.ar/portfolio/simpsons/",
    description1: "Frases de Los Simpsons",
    description2: "Frontend with react and Bootstrap",
    tech: ["react", "bootstrap"],
  },
];
